<x-admin-main page="Stock Count">
    <x-slot name="header">@vite(['resources/css/app.css', 'resources/css/styles.min.css', 'resources/css/myStyle.css', 'resources/js/app.js', 'resources/js/admin/inventory.js'])</x-slot>
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full" data-sidebar-position="fixed" data-header-position="fixed">
        <x-admin-sidebar /><div class="body-wrapper"><x-admin-topbar /><div class="body-wrapper-inner"><div class="container-fluid">
            <div class="d-flex justify-content-between align-items-center mt-4"><h4><b>Stock Count</b></h4><a href="{{ route('admin.inventory.index') }}" class="btn btn-transparent">Back</a></div><hr>
            <form action="{{ route('admin.inventory.stock-count.store') }}" method="POST" onsubmit="disableSubmitButton(this)">@csrf
                <div class="inputs-container shadow p-3 rounded" style="border: 1px solid #d4d9e4;"><div class="row">
                    <div class="col-12 mb-3"><label for="product_id" class="form-label">Product *</label><select id="product_id" name="product_id" class="form-select inventory-product-select @error('product_id') border-danger @enderror" data-placeholder="Select Product" required><option value=""></option>@foreach ($products as $product)<option value="{{ $product->id }}" data-quantity="{{ $product->inventory?->quantity ?? 0 }}" data-available-quantity="{{ $product->inventory?->availableQuantity() ?? 0 }}" data-average-cost="{{ $product->inventory?->average_cost ?? 0 }}" data-low-stock-alert="{{ $product->inventory?->low_stock_alert }}" @selected((string) old('product_id', $selectedProductId) === (string) $product->id)>{{ $product->sku }} - {{ $product->translations->first()?->name ?? $product->configurable?->translations->first()?->name ?? 'Product' }}</option>@endforeach</select>@error('product_id')<p class="text-danger">{{ $message }}</p>@enderror</div>
                    <div class="col-md-6 mb-3"><label class="form-label">System Quantity</label><input type="text" id="current_quantity" class="form-control" readonly></div><div class="col-md-6 mb-3"><label class="form-label">Available Quantity</label><input type="text" id="available_quantity" class="form-control" readonly></div><div class="col-md-6 mb-3"><label class="form-label">Current Average Cost</label><input type="text" id="current_average_cost" class="form-control" readonly></div><div class="col-md-6 mb-3"><label class="form-label">Low Stock Threshold</label><input type="text" id="current_low_stock_alert" class="form-control" readonly></div>
                    <div class="col-md-6 mb-3"><label for="counted_quantity" class="form-label">Counted Quantity *</label><input type="number" min="0" step="0.0001" id="counted_quantity" name="counted_quantity" class="form-control @error('counted_quantity') border-danger @enderror" value="{{ old('counted_quantity') }}" required>@error('counted_quantity')<p class="text-danger">{{ $message }}</p>@enderror</div>
                    <div class="col-md-6 mb-3"><label class="form-label">Difference</label><input type="text" id="stock_count_difference" class="form-control" readonly></div>
                    <div class="col-12 mb-3"><label for="notes" class="form-label">Notes *</label><textarea id="notes" name="notes" class="form-control @error('notes') border-danger @enderror" rows="3" required>{{ old('notes') }}</textarea>@error('notes')<p class="text-danger">{{ $message }}</p>@enderror</div>
                </div></div><div class="text-end mt-3"><button type="submit" class="btn btn-primary"><i class="ti ti-device-floppy me-1"></i><span class="btn-text">Save</span><span class="btn-loading d-none">Saving...</span></button></div>
            </form>
        </div></div></div>
    </div>
</x-admin-main>
